### ISSUE TITLE
Support for SteamDeck

### ISSUE THREAD

**Issue by S1lent-Gh0st** [v1993/evdevhook#13]
Hi

Would it be possible to make this package as Flatpak or AppImage to make it accessible on SteamDeck without Dev Mode and make configuration for SteamDeck Controller? I could provide logs or try to make config myself but right now I cannot compile evdevhook because SteamOS is missing dependencies for it and at least for now I couldn't find a way to unlock the filesystem.

**Comment by v1993** [comment]
I don't really plan to make flatpak/appimage releases, at least for now, but anyone interested is welcome to do so. I also won't be getting Steam Deck in foreseeable future, but will be happy to accept profile for it made by others.

**Comment by tjhorner** [comment]
It doesn't look like the drivers installed on the Steam Deck expose its gyro input via evdev.

Here are the devices detected by evtest:

<img width="442" alt="image" src="https://user-images.githubusercontent.com/2646487/159589211-f6f7fcda-9623-4a3b-ac54-0a8d970d2e85.png">

`event7` and `event8` are the default mouse and keyboard inputs respectively, used when Steam is closed so that there is a fallback to mouse and keyboard controls (similar to how the Steam Controller works).

`event7`:

<img width="520" alt="image" src="https://user-images.githubusercontent.com/2646487/159589318-74c38882-9745-4837-b0ba-775f2677323f.png">

`event8`:

<img width="523" alt="image" src="https://user-images.githubusercontent.com/2646487/159589341-b06ad2a1-6dac-4fcb-8a12-4169d49d6246.png">

I found [a library](https://github.com/ltjax/steam_controller) which works with the original Steam Controller and provides gyro data; I tried modifying it so that it recognizes the new vid/pid pair from the Steam Deck's internal controller. It didn't work, but I bet with a bit more reverse engineering this could be made to work with either evdev (e.g. a DKMS module) or have its own cemuhook server project.

Either way, it doesn't look like this is currently natively supported out of the box on Steam Deck.

**Comment by tjhorner** [comment]
>at least for now I couldn't find a way to unlock the filesystem.

@S1lent-Gh0st you can make the filesystem r/w with `steamos-readonly disable` at the command line, but note that any changes made to that filesystem will be overwritten by SteamOS updates in the future

**Comment by Jack-Sibley** [comment]
@tjhorner I've been looking into the raw hid output from the steam deck and it's slightly different from the og steam controller so I don't think existing libraries will save us here.

Not super relevant to evdevhook but for what it's worth I've gotten motion data piped into a cemuhook using a rust program but steam doesn't seem to like other programs accessing the deck hid while it's running so you can't use any of the other controls. My guess is we'll have to wait for proper evdev support from valve.

**Comment by tjhorner** [comment]
@Jack-Sibley I wonder if there is a way to capture existing HID events from programs that are currently using it exclusively, similar to a Windows filter driver. I don't want to pollute this project's issues with unrelated discussion, so do you want to move somewhere else? I am on [Telegram](https://t.me/bcrypt) and Discord (tj#1234) if you want to DM me there. If you know of any places that are into Steam Deck hacking then we can head there instead

**Comment by v1993** [comment]
This doesn't seem to really be related to evdevhook anymore - feel free to comment if they'll expose gyro as evdev device so I'll repoen the issue.

**Comment by BROHONKY** [comment]
It seems someone has made a dsu hook for the Steam Deck
https://github.com/kmicki/SteamDeckGyroDSU

**Comment by fbunau** [comment]
> It seems someone has made a dsu hook for the Steam Deck https://github.com/kmicki/SteamDeckGyroDSU

Thank you for commenting. I have been waiting for this for a long time
