### ISSUE TITLE
Doesn't work on Citra (3DS Emu)

### ISSUE THREAD

**Issue by yoyossef** [v1993/evdevhook#18]
Evdevhook works on Cemu and on the PadTest program (https://cemuhook.sshnuke.net/padudpserver.html), but it doesn't on Citra for some reason, the address and the port are correctly set.

It's easily reproducible, launch the evdevhook UDP server, open the Citra config menu, go to "Controls" settings, click on "Motion/Touch", set "CemuhookUDP" as the motion provider, test the config.

![image](https://user-images.githubusercontent.com/31565280/222820877-57084030-8584-4338-af9f-8d50bb743713.png)

**Comment by v1993** [comment]
Yeah, see https://github.com/v1993/evdevhook/discussions/17. At some point some external change caused evdevhook to break with some clients. I have a WIP sitting on hard drive that reimplements the entire thing using https://github.com/v1993/gcemuhook, sidestepping the issue by using a known working library instead of unique hacky implementation, but it still needs a lot of work before being usable and I'm currently busy with other stuff (most of it not related to either emulation or input). I'll hopefully eventually get to finish it...

**Comment by v1993** [comment]
See newly released [evdevhook2](https://github.com/v1993/evdevhook2).
